CREATE TABLE crop_parents (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(250) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE KEY UK_crop_parents (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;