CREATE TABLE `gps_orders` (
    id int unsigned NOT NULL AUTO_INCREMENT,
    firm int unsigned NOT NULL DEFAULT '0',
    car int unsigned NOT NULL DEFAULT '0',
    drv int unsigned NOT NULL DEFAULT '0',
    tech_op int unsigned NOT NULL DEFAULT '0',
    equip int unsigned NOT NULL DEFAULT '0',
    d_beg datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
    d_end datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
    created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user int unsigned NOT NULL DEFAULT '0',
    flags int unsigned NOT NULL DEFAULT '0',
    gps_id int unsigned NOT NULL DEFAULT '0',
    move_dst int unsigned NOT NULL DEFAULT '0' COMMENT 'Переезд',
    note varchar(1024) NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    KEY IX_firm (firm),
    KEY IX_car (car),
    KEY IX_tech_op (tech_op),
    KEY IX_equip (equip),
    KEY IX_beg (d_beg),
    KEY IX_end (d_end),
    KEY IX_created (created),
    KEY IX_updated (updated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;