CREATE TABLE processing_types (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE KEY UK_processing_types (`name`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;